### ISSUE TITLE
3 issues worth mentioning

### ISSUE THREAD

**Issue by Centilitre** [AOEpeople/Aoe_Scheduler#124]
Hello Fabrizio,

I had 3 issues when I installed your plugin v1.0.1 into my development server for the first time, 2 of issues could be avoided with little modification to your code:

<h2>1. Windows EOL problem:</h2>

After installing your plugin and adding the following line into crontab:
<pre>
MAILTO=myemail@email.com
* * * * * /bin/bash /path/to/scheduler_cron.sh
</pre>

I received emails with this message:
<pre>
/path/to/scheduler_cron.sh: line 2: $'\r': command not found
/path/to/scheduler_cron.sh: line 4: set: errexit
: invalid option name
/path/to/scheduler_cron.sh: line 5: $'\r': command not found
/path/to/scheduler_cron.sh: line 7: set: nounset
: invalid option name
/path/to/scheduler_cron.sh: line 8: $'\r': command not found
/path/to/scheduler_cron.sh: line 46: syntax error near unexpected token `$'in\r''
/path/to/scheduler_cron.sh: line 46: `    case "$1" in
'
</pre>
That is because my Linux development server is not happy the Windows EOL character ''\r'\n'. After converting the Windows EOL characters to Linux EOL (which can be easily done by Notepad++), the problem is solved.

<h2>2. PHP Version problem</h2>
This is an issue related to 1and1 shared servers, won't effect most people. In my 1and1 development server, right after fixing the first problem, I received emails with this message:
<pre>
X-Powered-By: PHP/4.4.9
Content-type: text/html

<b>Parse error</b>:  syntax error, unexpected T_STRING, expecting T_OLD_FUNCTION or T_FUNCTION or T_VAR or '}' in <b>/path/to/scheduler.php</b> on line <b>12</b>
</pre>

This is because 1and1 shared server has multiple php version installed, and the php command gives me PHP/4.4.9.
<pre>
[me@host:~] 11:46:28 $ which php
/usr/local/bin/php
[me@host:~] 11:46:33 $ ls -l /usr/local/bin/
lrwxrwxrwx 1 root root      4 Oct 22  2010 php -> php4
lrwxrwxrwx 1 root staff    14 Oct 22  2010 php4 -> ../../bin/php4
lrwxrwxrwx 1 root staff    14 Oct 22  2010 php5 -> ../../bin/php5
lrwxrwxrwx 1 root root     24 Dec 10  2013 php5.4 -> ../../lib/cgi-bin/php5.4
lrwxrwxrwx 1 root root     24 Dec 10  2013 php5.5 -> ../../lib/cgi-bin/php5.5
</pre>

To solve this problem, I edited scheduler_cron.sh and my crontab, and replaced 
<pre>which php</pre>
with 
<pre>which php5.5</pre>
If you know better ways to solve this problem, please let me know.

<h2>3. PHP header</h2>
So after fixing the previous problems, cron worked fine, but then it sent me emails that contained some HTTP headers (every minute):
<pre>
X-Powered-By: PHP/5.5.24
Set-Cookie: PHPSESSID=f2a45689a534d17f142972d051941117; expires=Wed, 10-Jun-2015 16:51:02 GMT; Max-Age=86400; path=/; HttpOnly
Expires: <b>Thu, 19 Nov 1981 08:52:00 GMT</b>
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-type: text/html
</pre>

I don't know why it shows 1981 but it is not causing problems to me ATM. 
To stop the header email, I edited scheduler_cron.php and added the option -q to suppress HTTP header output after the php comand:
<pre>
"${PHP_BIN}" <b>-q</b> "${SCHEDULER}" --action cron --mode ${MODE} ${OPTIONS}
</pre>

This issue didn't happen on my production server, so I guess it is because php is running as CGI on my development server. However, you can avoid this problem by adding the -q option.

That is it. There were the problem I had and the solutions. With little modification, you can avoid Problem 1 and 3 in the future. Hope it helps. 

Thanks for your wonderful module.
Kind Regards,

**Comment by fbrnc** [comment]
Hello @Centilitre,

thank you very much for your feedback. I'm not sure if I can help with any of this, but here are my thoughts:

1. Windows EOL problem:
`scheduler_cron.sh` already does have unix file endings. I thing the problem here is rather your version of of bash is complaining about the file in general. What version of bash are you running? (`bash --version`)

2. PHP Version problem:
I don't think we can assume that there's a php5.5 bin/link available so we shouldn't change this. Not sure how we can make this configurable in a clean way that respects multiple versions of PHP installed in parallel.

3. PHP header
Again, this seems to be specific to your setup. Looks like you're not executing php cli there. What does `php -v` output? Does it say something like `PHP 5.5.9-1ubuntu4.9 (cli)` (note the `(cli)`)?

**Comment by fcorriga** [comment]
1. Windows EOL problem can be fixed using dos2unix or sed
2. PHP Version problem is a non problem. PHP5 is mainstream so you just have to update your alternatives to use PHP5 as default PHP CLI interpreter and use PHP4 when needed.
3. You can create a separate file crontab file for the scheduler and add MAILTO="" at beginning to tell cron to send no emails. If it still sends mail then it's because PHP is sending some output to stdout. You can redirect that output to /dev/null adding >/dev/null 2>&1 at the end of your scheduler_cron.sh line
