### ISSUE TITLE
Pay attention to cron time

### ISSUE THREAD

**Issue by ADDISON74** [AOEpeople/Aoe_Scheduler#167]
By default "core_email_queue_clean_up" cron time is set up as follows: 0 0 * * * 

This created me trouble. Both "core_email_queue" and "core_email_queue_recipients" tables in Magento databases still have rows inside.

Changing cron time for "core_email_queue_clean_up" to * * * * * things are back to normal. Emails are sent. Emails and Recipients are deleted from both tables.

**Comment by fbrnc** [comment]
Hi @ADDISON74,

I'm not sure if I understand. `core_email_queue_clean_up` be default is configured to run once per day at midnight (`0 0 * * *`). Since this job only removes the sent emails I think this is ok and I don't see why you would need to run this job every minute.
Not sure if you're confusing this with `core_email_queue_send_all`, which actually sends out the emails and is configured to run every minute (`*/1 * * * *` which is a weird notation. This should be `* * * * *` or even better `always`)

However, I don't think any of these issues are related to Aoe_Scheduler, but if at all to Magento itself. But Aoe_Scheduler does allow you to update the records to whatever you need them to be.

I'm closing this issue for now. Feel free to reopen in case I'm missing something and you think there's something that needs to be done in Aoe_Scheduler.
