### ISSUE TITLE
1.9.2.2 issue.

### ISSUE THREAD

**Issue by dmcmillin** [AOEpeople/Aoe_Scheduler#194]
upon install on a clean testbed aoe_scheduler doesn't run. It just hangs up everything on the site. once disabled site resumes to function properly.

**Comment by robbieaverill** [comment]
Hey @dmcmillin  - what are your system specs? Is it possible that you're running a large indexer at the time, and it's chewing up all your system resources? What happens if you disable all cron jobs other than the `aoescheduler_heartbeat` task and try again? Would be worth watching your box stats as it's running to see what the CPU and memory consumption looks like as it's more likely to be an issue with overloading than with Magento 1.9.2.2 specifically.

**Comment by dmcmillin** [comment]
Thanks, I had not thought about that. Cleared cron and it worked like a
charm.

On Sat, Nov 14, 2015 at 11:06 PM, Robbie Averill <notifications@github.com>
wrote:

> Hey @dmcmillin <https://github.com/dmcmillin> - what are your system
> specs? Is it possible that you're running a large indexer at the time, and
> it's chewing up all your system resources? What happens if you disable all
> cron jobs other than the aoescheduler_heartbeat task and try again? Would
> be worth watching your box stats as it's running to see what the CPU and
> memory consumption looks like as it's more likely to be an issue with
> overloading than with Magento 1.9.2.2 specifically.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AOEpeople/Aoe_Scheduler/issues/194#issuecomment-156787667>
> .
>



-- 
Vasari Plaster and Stucco, LLC
Web Support Specialist
805-845-2497

**Comment by robbieaverill** [comment]
Glad you got it sorted :)
