### ISSUE TITLE
Optimize timeline for many processed jobs

### ISSUE THREAD

**Issue by ihor-sviziev** [AOEpeople/Aoe_Scheduler#195]
Hi,

We're using this extension on production, and time to time we doing some investigation that some issue happened. It requires to understand what's was ~10h ago with cron jobs, maybe some of them "stuck". For this purposes we configured cleanup complete tasks after 24h, as result we have timeline like this and it loads really long time. (rendering )

![image](https://cloud.githubusercontent.com/assets/1873745/11119093/d3f00a62-894f-11e5-874a-4a63c7c6df16.png)

Would be great to improve rendering time of this page. 

There is a lot manipulations with DOM. As example we may store information about all tasks in some variable and on hover we should get information from this variable and put to popup content.

**Comment by fbrnc** [comment]
I have some good news for you: This is happening right now (Issue: #158).
Checkout this branch: https://github.com/AOEpeople/Aoe_Scheduler/tree/issue/158_new_timeline
(Caution: This is still work in progress and experimental. For example the popup window is still missing. But feel free to test it and give me feedback if that works for you if you like).

**Comment by fbrnc** [comment]
Btw, if you're mostly interested in the failed jobs you should configure different values for cleaning up successful and failed builds. Also there's an option to only keep a fixed number of successful jobs instead of a fixed time frame. This should significantly reduce the number of DOM elements even with the existing version.
