### ISSUE TITLE
Base table or view not found: 1146 Table 'catalog_product_entity_tmp_indexer'

### ISSUE THREAD

**Issue by gnickoloff** [AOEpeople/Aoe_Scheduler#206]
Seeing this on EE 1.14.2.1 with Scheduler 1.3.0:

Indexer job (enterprise_refresh_index) is failing with the attached trace. Manually reindexing from command line seems to fix the problem for a few hours, but then it starts failing again with the same trace.

[Exception_Log_2015-11-25_09:39:03.txt](https://github.com/AOEpeople/Aoe_Scheduler/files/43964/Exception_Log_2015-11-25_09.39.03.txt)

**Comment by robbieaverill** [comment]
Hi @gnickoloff 

If you're running enterprise edition, get in touch with Magento support and explain this situation to them.

They have a plethora of indexing related patches hidden away that they give out to EE customers who ask for them :)

From memory of having this issue myself, it happens when the following happens (core Magento behaviour, not scheduler related):

1. Indexer starts
2. Indexer builds up a temporary product data table
3. Indexer renames table to a legitimate flat table name
4. *Indexer process dies*
5. Next indexer tries to start, but cannot create the table because the constraint names already exist in the database

The patch they gave me for this issue changed the way they name the table constraints, so it's no longer a fatal error.

R

**Comment by gnickoloff** [comment]
Thanks.

I went around and around with Magento and they finally sent me over a patch that fixed the problem. They insisted that the problem was with the scheduler, so I had to disable it and let the indexer puke out a few times on its own before they came around.

Once I installed the patch, I re-enabled the scheduler and all has been perfect since.
