### ISSUE TITLE
CRON using runNow

### ISSUE THREAD

**Issue by fslzia** [AOEpeople/Aoe_Scheduler#209]
Hi,
I am running CRON job using runNow using below code.

    $schedule = Mage::getModel('cron/schedule'); 
    $schedule->setJobCode('orders_export');
    $schedule->setScheduledReason('Testing CRON');
    $schedule->runNow(false);
    $schedule->save();

Problem is that call is not asynchronous, it stucks at runNow until job is complete. Can someone suggest what to do?

Can we also pass parameters to CRON job using AOE?

**Comment by fbrnc** [comment]
HI @fslzia,

yes, that's totally possible: Instead of `$schedule->runNow(false);` you should do `$schedule->schedule();` (Optionally you can pass a timestamp in the future if you don't want to execute it right away):

```
$schedule = Mage::getModel('cron/schedule'); /* @var $schedule Aoe_Scheduler_Model_Schedule */
$schedule->setJobCode('orders_export');
$schedule->setScheduledReason('Testing CRON');
$schedule->schedule();
$schedule->save();
```

Passing parameters is also possible. You can pass any value (it's up to you to come up with a format)
```$schedule = Mage::getModel('cron/schedule'); /* @var $schedule Aoe_Scheduler_Model_Schedule */
$schedule->setJobCode('orders_export');
$schedule->setScheduledReason('Testing CRON');
$schedule->setParameters('Hello World'):
$schedule->save();
```

And then in the job you can access the parameters like this:
```
class Aoe_Scheduler_Model_Task_Test {

    public function run(Aoe_Scheduler_Model_Schedule $schedule) {
        $parameters = $schedule->getParameters();
		[...]
	}
}
```
(Find this an example in app/code/community/Aoe/Scheduler/Model/Task/Test.php)

**Comment by fslzia** [comment]
Hi @fbrnc,

Thanks for providing these details. I really appreciate your help. This is what I needed.

**Comment by fslzia** [comment]
Hi @fbrnc,

One more question. The job I have added is called from a button to export orders. There is a possibility that users do this more than once or different users are requesting export. So I need to run multiple instances of same job.

Can we do this? Currently if I add 2nd job with same job code, it is skipped.

If this is not possible, can we create jobs at rutime with unique job code so that we don't have to add job information in Cron tab and give them unique name to trick system that these are different.

Many Thanks

**Comment by fbrnc** [comment]
HI @fslzia,

this is not possible by design, since the since those cron tasks are "idempotent-ish" (it shouldn't matter how often you call them).
Looks what you're really trying to do is implementing a queue. And you CAN use Aoe_Scheduler to process a queue. 
You might want to check out my Aoe_Queue module (https://github.com/AOEpeople/Aoe_Queue) that already comes with an Aoe_Scheduler task.
Hope this helps.
Cheers,
Fabrizio

**Comment by fslzia** [comment]
Hi @fbrnc,

Thanks for providing details. I will take a look at Aoe_Queue.

Best Regards,
