### ISSUE TITLE
page does now show content on back end? cannot view timeline or list view data etc

### ISSUE THREAD

**Issue by EmpDirect** [AOEpeople/Aoe_Scheduler#262]
Hi,

I will try and attach a screenshot showing back end.

On the back end I can no longer see the Job Configuration, List View, Timeline View or Instructions under configuration>scheduler?!

See screenshot - it says "Scheduler is working. (Last heart beat: xx minute(s) ago)" but I see no content on page.

(I have tried multiple web browsers)

---

Cron jobs are running.

Server hosts have investigated and cannot advise me.

---

Any ideas please?

![nocontentbackend](https://cloud.githubusercontent.com/assets/18741293/14922461/a1746b9a-0e2f-11e6-9d3c-5015590e742e.JPG)
?

**Comment by EmpDirect** [comment]
from my cpanel:

root@merian [~]# crontab -l -u emporium 
SHELL="/usr/local/cpanel/bin/jailshell"
*/15 * * * * php -q /home/emporium/public_html/cron.php

*/25 * * * * php /home/emporium/public_html/shell/indexer.php --reindex catalog_product_price,cataloginventory_stock > /dev/null 2>&1

25 2 * * * php /home/emporium/public_html/shell/indexer.php --reindexall > /dev/null 2>&1

*/5 * * * * ! test -e /home/emporium/public_html/maintenance.flag && /bin/bash /home/emporium/public_html/scheduler_cron.sh --mode always

*/5 * * * * ! test -e /home/emporium/public_html/maintenance.flag && /bin/bash /home/emporium/public_html/scheduler_cron.sh --mode default

**Comment by fbrnc** [comment]
Hi @EmpDirect,
looks like Magento's not resolving the symlinks to the block template anymore. Have you changed any settings (especially the "allow symlinks" one?) How did you install the module in the first place? Via modman?
Also, it looks like this isn't the latest version of Aoe_Scheduler, because this would be detected and another message with instructions on how to fix that settings would be displayed.

Please update to the latest version (from GitHub, not Magento Connect) and let me know if the problem continues to exist.

Have a great day,
Fabrizio

**Comment by EmpDirect** [comment]
@Fabrizio Thanks so much @Fabrizio, I was pushing our server hosts for a resolution regarding cron job set up and they told me they changed a setting. This is when the problem starting with  AOE scheduler not showing on back end.

So again today I have pressed them for more information and upon their investigations this afternoon they found that they had inadvertently disable the AOE scheduler module!

This has now been re-enabled and is all working again on the back end!
