### ISSUE TITLE
Scheduler Time line takes ages to build

### ISSUE THREAD

**Issue by hgpit** [AOEpeople/Aoe_Scheduler#286]
Hello,

EE v1.14.2.4, PHP7 (also in PHP5.6)

We have just installed this extension and am finding it invaluable already! However, we have found a problem!

From Magento Admin, if I go to the '**System**'...'**Scheduler**'...'**Timeline View**' option, the timeline takes over 15 minutes to build (possibly longer - it's still building as I type this!), hogging my Magento Admin panel! It's obviously because there are errors in one of the tasks - but can this speed be fixed?

**Really slow build and broken CSS:**
![slow_time_line](https://cloud.githubusercontent.com/assets/16598973/17170901/22e30136-53e6-11e6-8a44-82d7a7e6bfb9.JPG)

Also (dunno if it's another symptom of the main problem), it appears to bork the Admin GUI CSS.
As you can see from the following image, where, with our normal view, the Magento logo isn't squashed and the menu text etc is smaller. Just viewing the '**Timeline View**' seems to screw up the CSS.

**Normal/correct CSS:**
![normalcss](https://cloud.githubusercontent.com/assets/16598973/17171072/f2dac6da-53e6-11e6-9ce9-b454d9ef8f34.JPG)

Thanks

Elliot

**Comment by fbrnc** [comment]
Hi @hgpit,
the current version of Aoe_Scheduler tries to load all schedules at ones (I have plans to change this, but this isn't coming in the near future). 
A simple workaround is to configure the number of schedules the should be kept so that the collection doesn't get too big while loading:

![grafik](https://cloud.githubusercontent.com/assets/468820/21133339/aaaa7096-c118-11e6-8b2f-035e8e1a6fd6.png)
