### ISSUE TITLE
Cannot run the scheduler_cron.sh

### ISSUE THREAD

**Issue by quyna** [AOEpeople/Aoe_Scheduler#294]
Hi Support 
I tried to run the scheduler_cron.sh manualy but I got the error message below

[root@www ~]# : command not founderce/scheduler_cron.sh: line 2:
[root@www ~]# : invalid option namece/scheduler_cron.sh: line 4: set: nounset

I am using:
PHP Version 5.4.45
Aoe_Scheduler   1.3.0 (stable) 

I look forward to hearing from you.
Thanks

**Comment by wsfsb** [comment]
Found the same issue.  According to Cpanel support the script is not working after a WHM update from ver 58 build 29 because of the following:
"For your first script (AOE Scheduler), you are experiencing issues because the 'which php' command in the script relies on php, not php-cli, however, it relies on PHP acting like php-cli. This is a change that was made to resolve an issue of backwards compatibility with EasyApache 3."
Can we get an update on this?

**Comment by daschenbrener** [comment]
I have the same issue as well, would like to know if there is a work around for this.

Thanks in advance

**Comment by markus-simon** [comment]
sounds like this might help you:

`cat scheduler_cron.sh | tr -d '\r' > fixedscript.sh`

**Comment by bridgesense** [comment]
Before the cPanel update there was most likely a cron job already in process that was aborted prematurely.  Be sure to remove any of the current lock files in the tmp directory before spending too much time on this.

`
rm -rf /tmp/magento*.lock
`

**Comment by tmotyl** [comment]
fixed with https://github.com/AOEpeople/Aoe_Scheduler/commit/280609348f3fa2db47994cfa3a22cb36806cb41d
now you can pass path to binary as a param
