### ISSUE TITLE
Confused about groups

### ISSUE THREAD

**Issue by OvalMedia** [AOEpeople/Aoe_Scheduler#357]
I am confused about how to set up the groups.

I have 2 jobs (stock update and order export) that should always run on time. Both are usually done within seconds or very few minutes.
I have 1 big job that sometimes takes up to an hour (product import). This one should not block the first 2 jobs from executing.
Then there is a fourth job (https://github.com/magento-hackathon/AsyncIndex) which updates the index periodically via cron. This one should never run while the product import ist running as it would slow it down drastically and be redundant anyway. 

So my idea so far...

Group 1: stockupdate
Group 2: orderexport
Group 3: productimport
Group 4: asyncindex

How would I need to setup my crontab so that productimport and asyncindex never run at the same time?

Thank you

**Comment by kuldeepdaffodil** [comment]
A more detail documentation required on grouping.
Thank you

**Comment by m-overlund** [comment]
Grouping is for running specific cron tasks in separate processes - so for instance product import won't block other tasks because they're running in the same process and has to finish before the other tasks can begin.

If group `productimport` and `asyncindex` never should run at the same time, you have to adjust the cron expressions accordingly.

Groups only separates the processes.

Another solution could be to not schedule `asyncindex` and instead add it to the `productimport` under `Run jobs on success` so it will only be scheduled after productimport is finished.
