### ISSUE TITLE
Run Now action under Schedule Configuration

### ISSUE THREAD

**Issue by davidtay** [AOEpeople/Aoe_Scheduler#50]
There used to be a Run Now action under the Schedule Configuration grid. What happend to it?

**Comment by davidtay** [comment]
Never mind, see it under the Cron configuration.

**Comment by fbrnc** [comment]
Also, I've disabled "run now" by default in the latest (unmerged) version of Aoe_Scheduler, since it might not work as expected if run from the Magento backend (e.g. memory or execution time limitation). I suggest always do "schedule now" and let cron pick it up. Of course that might be annoying during development and testing. That's why you can enable the settings in the configuration.

**Comment by aydus** [comment]
Thanks.
