### ISSUE TITLE
Empty Timeline View

### ISSUE THREAD

**Issue by marcoschierhorn** [AOEpeople/Aoe_Scheduler#59]
First of all thanks for this great Extension. 
I'm currently running into the "too late for schedule" issue. I have set the cron to be executed every minute. But it seems that I have some long running jobs every night. I tried to analyze this through using the timeline view. But unfortunately it's empty / shows nothing in the div. I have attached a screenshot, so that you can see what I'm talking about :)
I was also looking if some elements couldn't be loaded in Firebug, but there are no errors displayed. 
Do you need any additional information?

![empty_timelineview](https://cloud.githubusercontent.com/assets/384813/6425641/9e17d05a-bf33-11e4-9e8b-65a6a511d903.jpg)

**Comment by fbrnc** [comment]
Hi Marco,

did you install the module via modman? Did you allow symlinks for block templates? (https://github.com/colinmollenhour/modman#requirements)

If you still can't see anything then this is probably a bug in Aoe_Scheduler. I'll release a new major version of Aoe_Scheduler this week and a lot of things have changed. There's a great chanced that this problem is solved (if it's related to too many jobs to be displayed at the same time).

Please update to the new version once it is out and let me know if this fixed your problem. If not I'm happy to have a closer look at this.

Have a great day,
Fabrizio

**Comment by fbrnc** [comment]
Did this solve your problem?

**Comment by marcoschierhorn** [comment]
Hi Fabrizio, thanks a lot for your answers. I really appreciate that!
After disabling and enabling the symlink setting and updating your great extension it works!
Please accept my apology that I wasn't able to answer before and thanks again for your great work and your efforts
